### ISSUE TITLE
Get Qi running on windows

### ISSUE THREAD

**Issue by galdar496** [galdar496/QiGameEngine#17]
Likely run into a couple of cross-platform issues (16-byte alignment comes to mind) but should be very straightforward. Also need to build a windows version of gtest (https://code.google.com/p/googletest/)

**Comment by galdar496** [comment]
To align to 16 bytes on windows, you can use 

``` c++
__declspec(align(16))
```

**Comment by msgambati** [comment]
I found this. What do you think?

```
#if defined(_MSC_VER)
#define ALIGNED_(x) __declspec(align(x))
#else
#if defined(__GNUC__)
#define ALIGNED_(x) __attribute__ ((aligned(x)))
#endif
#endif

#define _ALIGNED_TYPE(t,x) typedef t ALIGNED_(x)

//SOME USAGE SAMPLES

ALIGNED_TYPE_(double, 16) aligned_double_t;

ALIGNED_TYPE_(struct, CACHE_LINE) tagALIGNEDSTRUCT
{
    //STRUCT MEMBERS GO HERE
}aligned_struct_t;

ALIGNED_TYPE_(union, CACHE_LINE) tagALIGNEDUNION
{
    //UNION MEMBERS GO HERE

}aligned_union_t;
```

**Comment by galdar496** [comment]
This looks great, just pit QI_ in front of it.

**Comment by galdar496** [comment]
I guess I would expect it to look like this (in the Defines.h file):

``` c++
#if defined(QI_WINDOWS) // where we define QI_WINDOWS in the Defines.h file above this line
   #define QI_ALIGN(x) __declspec(align(x))
#else
   #define QI_ALIGN(x) __attribute__ ((aligned(x))) // works on linux and mac
#endif

// Example use
class QI_ALIGN(16) Vec4 {};
```

Note that I didn't test this or write it in a compiler, but that's how I think it should generally look.

**Comment by galdar496** [comment]
Turns out this is unnecessary. C++11 has support for _alignas()_ which will already be cross-platform: http://en.cppreference.com/w/cpp/language/alignas

**Comment by galdar496** [comment]
d3fba63c9265d47baeb4186e4fdba53a10e3738e
