### ISSUE TITLE
Discuss line ending conversion/format for github

### ISSUE THREAD

**Issue by msgambati** [galdar496/QiGameEngine#26]

**Comment by galdar496** [comment]
All files should use \n line endings. Every OS will support that, only
windows adds \n\r which will confuse Unix systems.

**Comment by galdar496** [comment]
Turns out you can get git to do this for you automatically based on your OS: https://help.github.com/articles/dealing-with-line-endings/

**Comment by galdar496** [comment]
echo "\* text=auto" > .gitattributes 
git add .gitattributes 
git commit -m 'adding .gitattributes for unified line-ending'

**Comment by galdar496** [comment]
http://adaptivepatchwork.com/2012/03/01/mind-the-end-of-your-line/

**Comment by galdar496** [comment]
Added a .gitattributes files in the base folder. 874d57867d2399fc8d964e71d3ad30549561f6cc
